package com.conmigo.app.bbdd.jpa;
// Generated Apr 21, 2018 8:15:12 AM by Hibernate Tools 5.2.8.Final

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChatId generated by hbm2java
 */
@Embeddable
public class ChatId implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long event;
    private long sender;
    private long receiver;
    private LocalDateTime date;

    public ChatId() {
    }

    public ChatId(final long event, final long sender, final long receiver, final LocalDateTime date) {
        this.event = event;
        this.sender = sender;
        this.receiver = receiver;
        this.date = date;
    }

    @Column(name = "EVENT", nullable = false)
    public long getEvent() {
        return event;
    }

    public void setEvent(final long event) {
        this.event = event;
    }

    @Column(name = "SENDER", nullable = false)
    public long getSender() {
        return sender;
    }

    public void setSender(final long sender) {
        this.sender = sender;
    }

    @Column(name = "RECEIVER", nullable = false)
    public long getReceiver() {
        return receiver;
    }

    public void setReceiver(final long receiver) {
        this.receiver = receiver;
    }

    @Column(name = "DATE", nullable = false, length = 19)
    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(final LocalDateTime date) {
        this.date = date;
    }

    @Override
    public boolean equals(final Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof ChatId)) {
            return false;
        }
        ChatId castOther = (ChatId) other;

        return getEvent() == castOther.getEvent() && getSender() == castOther.getSender()
                && getReceiver() == castOther.getReceiver() && (getDate() == castOther.getDate()
                        || getDate() != null && castOther.getDate() != null && getDate().equals(castOther.getDate()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) getEvent();
        result = 37 * result + (int) getSender();
        result = 37 * result + (int) getReceiver();
        result = 37 * result + (getDate() == null ? 0 : getDate().hashCode());
        return result;
    }

}
