package com.conmigo.app.bbdd.jpa;
// Generated Apr 21, 2018 8:15:12 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChatId generated by hbm2java
 */
@Embeddable
public class ChatId implements java.io.Serializable {

    private long event;
    private long sender;
    private long receiver;
    private Date date;

    public ChatId() {
    }

    public ChatId(long event, long sender, long receiver, Date date) {
        this.event = event;
        this.sender = sender;
        this.receiver = receiver;
        this.date = date;
    }

    @Column(name = "EVENT", nullable = false)
    public long getEvent() {
        return this.event;
    }

    public void setEvent(long event) {
        this.event = event;
    }

    @Column(name = "SENDER", nullable = false)
    public long getSender() {
        return this.sender;
    }

    public void setSender(long sender) {
        this.sender = sender;
    }

    @Column(name = "RECEIVER", nullable = false)
    public long getReceiver() {
        return this.receiver;
    }

    public void setReceiver(long receiver) {
        this.receiver = receiver;
    }

    @Column(name = "DATE", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ChatId))
            return false;
        ChatId castOther = (ChatId) other;

        return (this.getEvent() == castOther.getEvent()) && (this.getSender() == castOther.getSender())
                && (this.getReceiver() == castOther.getReceiver()) && ((this.getDate() == castOther.getDate())
                        || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(castOther.getDate())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getEvent();
        result = 37 * result + (int) this.getSender();
        result = 37 * result + (int) this.getReceiver();
        result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
        return result;
    }

}
