package com.conmigo.app.bbdd.jpa;
// Generated 16-feb-2017 12:22:59 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "combo", catalog = "conmigodb")
public class Combo extends GenericEntity<Long> {

    private static final long serialVersionUID = 1L;

    protected Long id;
    protected String name;
    protected String value;
    protected String type;

    public Combo() {
    }

    public Combo(final long createdBy, final Date createdDate) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }

    public Combo(final Long id, final String name, final String value, final String type) {
        super();
        this.id = id;
        this.name = name;
        this.value = value;
        this.type = type;
    }

    @Override
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    @Override
    public void setId(final Long id) {
        this.id = id;
    }

    @Column(name = "NAME", length = 50)
    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    @Column(name = "VALUE", length = 50)
    public String getValue() {
        return value;
    }

    public void setValue(final String value) {
        this.value = value;
    }

    @Column(name = "TYPE", length = 50)
    public String getType() {
        return type;
    }

    public void setType(final String type) {
        this.type = type;
    }

}
