package com.conmigo.app.bbdd.jpa;
// Generated 24-feb-2017 10:37:08 by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table( name = "message", catalog = "conmigodb" )
public class Message extends GenericEntity<Long> {

	private static final long serialVersionUID = 1L;
	private Long id;
	private User userBySender;
	private User userByReceiver;
	private String message;
	private Date date;

	public Message() {
	}

	public Message( final User userBySender, final User userByReceiver ) {
		this.userBySender = userBySender;
		this.userByReceiver = userByReceiver;
	}

	public Message( final User userBySender, final User userByReceiver, final String message, final Date date, final Long createdBy, final Date createdDate, final Long lastModifiedBy, final Date lastModifiedDate ) {
		this.userBySender = userBySender;
		this.userByReceiver = userByReceiver;
		this.message = message;
		this.date = date;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Override
	@Id
	@GeneratedValue( strategy = IDENTITY )
	@Column( name = "ID", unique = true, nullable = false )
	public Long getId() {
		return id;
	}

	@Override
	public void setId( final Long id ) {
		this.id = id;
	}

	@ManyToOne( fetch = FetchType.LAZY )
	@JoinColumn( name = "SENDER", nullable = false )
	public User getUserBySender() {
		return userBySender;
	}

	public void setUserBySender( final User userBySender ) {
		this.userBySender = userBySender;
	}

	@ManyToOne( fetch = FetchType.LAZY )
	@JoinColumn( name = "RECEIVER", nullable = false )
	public User getUserByReceiver() {
		return userByReceiver;
	}

	public void setUserByReceiver( final User userByReceiver ) {
		this.userByReceiver = userByReceiver;
	}

	@Column( name = "MESSAGE", length = 65535 )
	public String getMessage() {
		return message;
	}

	public void setMessage( final String message ) {
		this.message = message;
	}

	@Temporal( TemporalType.TIMESTAMP )
	@Column( name = "DATE", length = 19 )
	public Date getDate() {
		return date;
	}

	public void setDate( final Date date ) {
		this.date = date;
	}

}
