package com.conmigo.app.bbdd.jpa;
// Generated Apr 21, 2018 11:43:36 PM by Hibernate Tools 5.2.8.Final

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "conmigodb")
public class Message extends GenericEntity<Long> {

    private static final long serialVersionUID = 1L;
    private Chatroom chatroom;
    private long sender;
    private String text;
    private LocalDateTime date;

    public Message() {
    }

    public Message(final long id, final Chatroom chatroom, final long sender, final LocalDateTime date, final long createdBy,
            final LocalDateTime createdDate) {
        this.id = id;
        this.chatroom = chatroom;
        this.sender = sender;
        this.date = date;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }

    public Message(final long id, final Chatroom chatroom, final long sender, final String text, final LocalDateTime date,
            final long createdBy, final LocalDateTime createdDate, final Long lastModifiedBy,
            final LocalDateTime lastModifiedDate, final Boolean enable) {
        this.id = id;
        this.chatroom = chatroom;
        this.sender = sender;
        this.text = text;
        this.date = date;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
        this.enable = enable;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CHATROOM", nullable = false)
    public Chatroom getChatroom() {
        return chatroom;
    }

    public void setChatroom(final Chatroom chatroom) {
        this.chatroom = chatroom;
    }

    @Column(name = "SENDER", nullable = false)
    public long getSender() {
        return sender;
    }

    public void setSender(final long sender) {
        this.sender = sender;
    }

    @Column(name = "TEXT", length = 65535)
    public String getText() {
        return text;
    }

    public void setText(final String text) {
        this.text = text;
    }

    @Column(name = "DATE", nullable = false, length = 19)
    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(final LocalDateTime date) {
        this.date = date;
    }

}
