package com.conmigo.app.bbdd.jpa;
// Generated 17-feb-2017 15:47:50 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userprofile generated by hbm2java
 */
@Entity
@Table( name = "userprofile", catalog = "conmigodb" )
public class Userprofile implements java.io.Serializable {

	private String userId;
	private String email;
	private String firstName;
	private String lastName;
	private String name;
	private String username;

	public Userprofile() {
	}

	public Userprofile( String userId ) {
		this.userId = userId;
	}

	public Userprofile( String userId, String email, String firstName, String lastName, String name, String username ) {
		this.userId = userId;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.name = name;
		this.username = username;
	}

	@Id

	@Column( name = "userId", unique = true, nullable = false )
	public String getUserId() {
		return this.userId;
	}

	public void setUserId( String userId ) {
		this.userId = userId;
	}

	@Column( name = "email" )
	public String getEmail() {
		return this.email;
	}

	public void setEmail( String email ) {
		this.email = email;
	}

	@Column( name = "firstName" )
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName( String firstName ) {
		this.firstName = firstName;
	}

	@Column( name = "lastName" )
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName( String lastName ) {
		this.lastName = lastName;
	}

	@Column( name = "name" )
	public String getName() {
		return this.name;
	}

	public void setName( String name ) {
		this.name = name;
	}

	@Column( name = "username" )
	public String getUsername() {
		return this.username;
	}

	public void setUsername( String username ) {
		this.username = username;
	}

}
