package com.conmigo.app.bbdd.jpa;
// Generated 17-feb-2017 15:47:50 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Userconnection generated by hbm2java
 */
@Entity
@Table( name = "userconnection", catalog = "conmigodb", uniqueConstraints = @UniqueConstraint( columnNames = { "userId", "providerId", "rank" } ) )
public class Userconnection implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private UserconnectionId id;
	private int rank;
	private String displayName;
	private String profileUrl;
	private String imageUrl;
	private String accessToken;
	private String secret;
	private String refreshToken;
	private Long expireTime;

	public Userconnection() {
	}

	public Userconnection( final UserconnectionId id, final int rank, final String accessToken ) {
		this.id = id;
		this.rank = rank;
		this.accessToken = accessToken;
	}

	public Userconnection( final UserconnectionId id, final int rank, final String displayName, final String profileUrl, final String imageUrl, final String accessToken, final String secret, final String refreshToken, final Long expireTime ) {
		this.id = id;
		this.rank = rank;
		this.displayName = displayName;
		this.profileUrl = profileUrl;
		this.imageUrl = imageUrl;
		this.accessToken = accessToken;
		this.secret = secret;
		this.refreshToken = refreshToken;
		this.expireTime = expireTime;
	}

	@EmbeddedId

	@AttributeOverrides( { @AttributeOverride( name = "userId", column = @Column( name = "userId", nullable = false ) ), @AttributeOverride( name = "providerId", column = @Column( name = "providerId", nullable = false ) ),
			@AttributeOverride( name = "providerUserId", column = @Column( name = "providerUserId", nullable = false ) ) } )
	public UserconnectionId getId() {
		return id;
	}

	public void setId( final UserconnectionId id ) {
		this.id = id;
	}

	@Column( name = "rank", nullable = false )
	public int getRank() {
		return rank;
	}

	public void setRank( final int rank ) {
		this.rank = rank;
	}

	@Column( name = "displayName" )
	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName( final String displayName ) {
		this.displayName = displayName;
	}

	@Column( name = "profileUrl", length = 512 )
	public String getProfileUrl() {
		return profileUrl;
	}

	public void setProfileUrl( final String profileUrl ) {
		this.profileUrl = profileUrl;
	}

	@Column( name = "imageUrl", length = 512 )
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl( final String imageUrl ) {
		this.imageUrl = imageUrl;
	}

	@Column( name = "accessToken", nullable = false, length = 1024 )
	public String getAccessToken() {
		return accessToken;
	}

	public void setAccessToken( final String accessToken ) {
		this.accessToken = accessToken;
	}

	@Column( name = "secret" )
	public String getSecret() {
		return secret;
	}

	public void setSecret( final String secret ) {
		this.secret = secret;
	}

	@Column( name = "refreshToken" )
	public String getRefreshToken() {
		return refreshToken;
	}

	public void setRefreshToken( final String refreshToken ) {
		this.refreshToken = refreshToken;
	}

	@Column( name = "expireTime" )
	public Long getExpireTime() {
		return expireTime;
	}

	public void setExpireTime( final Long expireTime ) {
		this.expireTime = expireTime;
	}

}
