<%@ include file="../tiles/view/taglib.jsp"%>
<p>Aviso legal y pol&iacute;tica de privacidad<br />
En cumplimiento con lo establecido en la normativa de protecci&oacute;n de datos de Espa&ntilde;a y, en<br />
particular, en el art&iacute;culo 5 de la Ley Org&aacute;nica 15/1999, de 13 de diciembre, de Protecci&oacute;n de<br />
Datos de Car&aacute;cter Personal, informamos que todos los datos de car&aacute;cter personal que aporten<br />
los usuarios en el proceso de registro como durante la navegaci&oacute;n o uso del CONMIGO, y los<br />
datos derivados, si es el caso, del registro usando su cuenta de Facebook o Google, ser&aacute;n<br />
recogidos en un fichero cuyo responsable es Conmigo.<br />Conmigo utilizar&aacute; los datos recopilados para:<br />
- Formalizar el alta del usuario.<br />
- Prestar los servicios que el usuario haya solicitado<br />
- Gestionar la cuenta de usuario.<br />
- Comunicarnos con el usuario ante incidencias e informaci&oacute;n &uacute;til averca de Conmigo.<br />
- Env&iacute;o de comunicaci&oacute;n comercial de Conmigo o de terceros, siendo cedidos sus datos<br />
para que puedan ofrecer sus productos o servicio.<br />- Realizar acciones de mejora, actualizaciones, personalizaci&oacute;n de contenidos o reparaci&oacute;n<br />de incidencias.<br />As&iacute;mismo informamos de que todos los datos recogidos acerca de IP as&iacute; como e resto de<br />identificadores obtenidos por su dispositivo de navegaci&oacute;n por Conmigo, se usar&aacute;n con fines<br />estad&iacute;stico y encaminados a mejorar la experiencia del usuario y ser&aacute;n recogidos en el fichero<br />anteriormente nombrado.<br />El usuario de Conmigo acepta el env&iacute;o de comunicaciones comerciales as&iacute; como la creaci&oacute;n de<br />un perfil basado en su experiencia en la comunidad Conmigo.<br />Todos los datos ser&aacute;n eliminados una vez se d&eacute; de baja al usuario (ya sea de forma voluntaria o<br />por ser expulsado de la comunidad), independientepente de la v&iacute;a por la que haya realizado el<br />alta. As&iacute;mismo, el usuario siempre puede solicitar la cancelaci&oacute;n o modificaci&oacute;n de sus datos,<br />poni&eacute;ndolo en conocimiento en el correo XXXXXXX@conmigo.com adjuntando fotocopia de su<br />DNI o documento identificativo v&aacute;lido equivalente, en los t&eacute;rminos establecidos en la LOPD y en el<br />Real Decreto 1720/2007, de 21 de diciembre, por el que se aprueba el Reglamento de desarrollo<br />de la LOPD. Igualmente, le recordamos la posibilidad de dirigir una reclamaci&oacute;n ante la Agencia<br />Espa&ntilde;ola de Protecci&oacute;n de datos de car&aacute;cter personal por el tratamiento de sus datos personales<br />realizado por Conmigo.<br />Sin embargo, y sin perjuicio de lo anterior,Conmigo conservar&aacute; datos meramente estad&iacute;sticos de<br />utilizaci&oacute;n por parte de los usuarios de sus recursos y herramientas as&iacute; como para dificulltar que<br />un usuario expulsado pueda volver a darse de alta.<br />Los datos recopilados podr&aacute;n ser cedidos a tercera empresas para el env&iacute;o de comunicaciones<br />comerciales, por lo que el usuario, con su regostro y uso de la comunidad acepta la cesi&oacute;n de sus<br />datos a terceras sociedades ajenas a Conmigo.<br />La comunidad no est&aacute; pensada ni dise&ntilde;ada para ser utilizada por menores de 18 a&ntilde;os, por lo que<br />&eacute;stos deber&aacute;n abstenerse de entrarm registrarse ni facilitar ning&uacute;n dato peronal. Conmigo se<br />reserva el derecho de comprobar la edad del usuario, y ya que ser mayor es un requisito obligado<br />en el registro, el usuario se compromete a:<br />- No dar datos falsos, ambiguos o de otras personas en su nombre.<br />- Mantener su perfil actualizado para no incurrir en el incumplimiento del punto anterior.<br />- Mantener como informaci&oacute;n secreta su contrase&ntilde;a de acceso a Conmigo ni ning&uacute;n dato<br />que pueda comprometer la segurisas de su perfil de usuario.</p>
<p>- Transferir su perfil de usuario EN NING&Uacute;N CASO. Debe efectuarse la baja del usuario y el<br />
alta del nuevo.<br />- Permanecer en la comunidad siguiendo las Buenas pr&aacute;cticas de Conmigo, entendiendo<br />
que cualquier hehco que consta como penalizado puede acarrear acciones legales, avisos<br />
de comportamiento o la expulsi&oacute;n del usuario.<br />
- Ser responsable de sus comentarios, acciones y datos que facilite dentro de la comunidad<br />
Conmigo, as&iacute; como en las redes sociales. En este &uacute;ltimo caso, deber&aacute;s dirigirse a las<br />
redes sociales en las que haya participado para ejercer sus derechos de rectificaci&oacute;n,<br />
cancelaci&oacute;n y oposici&oacute;n de sus datos.<br />
Conmigo tiene implantadas las medidas de seguridad de &iacute;ndole t&eacute;cnica y organizativa necesarias<br />
para garantizar la seguridad de sus Datos de Car&aacute;cter Personal y evitar su alteraci&oacute;n, p&eacute;rdida,<br />
tratamiento y/o acceso no autorizado, habida cuenta del estado de la tecnolog&iacute;a, la naturaleza de<br />
los datos almacenados y los riesgos a que est&aacute;n expuestos, ya provengan de la acci&oacute;n humana o<br />
del medio f&iacute;sico o natural.</p>