package com.conmigo.app.dto;
// Generated 24-feb-2017 10:37:08 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

/**
 * Message generated by hbm2java
 */
public class MessageDto extends GenericDto<Long> {

    private static final long serialVersionUID = 1L;
    private Long id;
    private ChatroomDto chatroom;
    private long sender;
    private String text;
    private LocalDateTime date;

    public MessageDto() {
    }

    public MessageDto(final long id, final ChatroomDto chatroom, final long sender, final LocalDateTime date,
            final long createdBy, final LocalDateTime createdDate) {
        this.id = id;
        this.chatroom = chatroom;
        this.sender = sender;
        this.date = date;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }

    public MessageDto(final long id, final ChatroomDto chatroom, final long sender, final String text, final LocalDateTime date,
            final long createdBy, final LocalDateTime createdDate, final Long lastModifiedBy,
            final LocalDateTime lastModifiedDate, final Boolean enable) {
        this.id = id;
        this.chatroom = chatroom;
        this.sender = sender;
        this.text = text;
        this.date = date;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
        this.enable = enable;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(final Long id) {
        this.id = id;
    }

    public ChatroomDto getChatroom() {
        return chatroom;
    }

    public void setChatroom(final ChatroomDto chatroom) {
        this.chatroom = chatroom;
    }

    public long getSender() {
        return sender;
    }

    public void setSender(final long sender) {
        this.sender = sender;
    }

    public String getText() {
        return text;
    }

    public void setText(final String text) {
        this.text = text;
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(final LocalDateTime date) {
        this.date = date;
    }

}
