package com.conmigo.app.dto;
// Generated 24-feb-2017 10:37:08 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class MessageDto extends GenericDto<Long> {

	private static final long serialVersionUID = 1L;
	private Long id;
	private UserDto userBySender;
	private UserDto userByReceiver;
	private String message;
	private Date date;

	public MessageDto() {
	}

	public MessageDto( final UserDto userBySender, final UserDto userByReceiver ) {
		this.userBySender = userBySender;
		this.userByReceiver = userByReceiver;
	}

	public MessageDto( final UserDto userBySender, final UserDto userByReceiver, final String message, final Date date, final Long createdBy, final Date createdDate, final Long lastModifiedBy, final Date lastModifiedDate ) {
		this.userBySender = userBySender;
		this.userByReceiver = userByReceiver;
		this.message = message;
		this.date = date;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Override
	public Long getId() {
		return id;
	}

	@Override
	public void setId( final Long id ) {
		this.id = id;
	}

	public UserDto getUserBySender() {
		return userBySender;
	}

	public void setUserBySender( final UserDto userBySender ) {
		this.userBySender = userBySender;
	}

	public UserDto getUserByReceiver() {
		return userByReceiver;
	}

	public void setUserByReceiver( final UserDto userByReceiver ) {
		this.userByReceiver = userByReceiver;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage( final String message ) {
		this.message = message;
	}

	public Date getDate() {
		return date;
	}

	public void setDate( final Date date ) {
		this.date = date;
	}

}
