package com.conmigo.app.dto;
// Generated 22-feb-2017 8:12:26 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Role generated by hbm2java
 */
public class RoleDto extends GenericDto<Long> {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String name;
	private String description;

	public RoleDto() {
	}

	public RoleDto( final Long id ) {
		this.id = id;
	}

	public RoleDto( final String name, final String description, final Long createdBy, final Date createdDate, final Long lastModifiedBy, final Date lastModifiedDate ) {
		this.name = name;
		this.description = description;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Override
	public Long getId() {
		return id;
	}

	@Override
	public void setId( final Long id ) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName( final String name ) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription( final String description ) {
		this.description = description;
	}

}
